---
# tasks file for roles/ibm_sv_fc_create

- name: Get a list of volume mappings for the host
  ibm.spectrum_virtualize.ibm_svcinfo_command:
    command: "svcinfo lshostvdiskmap {{ host }}"
    clustername: "{{ clustername }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: mappings

- name: Get volume information for each volume mapped to the host
  ibm.spectrum_virtualize.ibm_svcinfo_command:
    command: "svcinfo lsvdisk {{ item.vdisk_name }} "
    clustername: "{{ clustername }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: volumes
  loop: "{{ mappings.stdout }}"

- name: Create a flashcopy consistency group
  ibm.spectrum_virtualize.ibm_svc_manage_consistgrp_flashcopy:
    clustername: "{{ clustername }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name:  "{{ prefix | upper }}_{{ host | upper }}"
    state: present

- name: Create flashcopy SNAPSHOT mapping to consistency group
  ibm.spectrum_virtualize.ibm_svc_manage_flashcopy:
    clustername: "{{ clustername }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name:  "{{ prefix | upper }}_{{ (item['stdout'] | from_json)[0].name }}"
    state: present
    copytype: "snapshot"
    source: "{{ (item['stdout'] | from_json)[0].name }}"
    target: "{{ prefix | upper }}_{{ (item['stdout'] | from_json)[0].name }}"
    mdiskgrp: "{{ (item['stdout'] | from_json)[0].mdisk_grp_name }}"
    consistgrp: "{{ prefix | upper }}_{{ host | upper }}"
  loop: "{{ volumes.results }}"
  when: fc_type == "snap"

- name: Create flashcopy CLONE mapping to consistency group
  ibm.spectrum_virtualize.ibm_svc_manage_flashcopy:
    clustername: "{{ clustername }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name:  "{{ prefix | upper }}_{{ (item['stdout'] | from_json)[0].name }}"
    state: present
    copytype: "clone"
    source: "{{ (item['stdout'] | from_json)[0].name }}"
    target: "{{ prefix | upper }}_{{ (item['stdout'] | from_json)[0].name }}"
    mdiskgrp: "{{ (item['stdout'] | from_json)[0].mdisk_grp_name }}"
    consistgrp: "{{ prefix | upper }}_{{ host | upper }}"
  loop: "{{ volumes.results }}"
  when: fc_type == "clone"
