---
# Create target flashcopy volumes for all volumes mapped to an existing host
# Create a flashcopy consistency groups and add the flashcopy mappings
# Start the flaschopy consistenccy group
#
# Requires the following to be specified on the ansible-playbook command:
#     --extra-vars
#         host=<"NAME OF HOST as defined on FlashSystem/Storwize/SVC">
#         clustername=<"NAME" or "IP ADDRESS OF FlashSystem/Storwize/SVC">
#         fc_type="snap" OR "clone" - Determines if this is a flashcopy snapshot or flashcopy clone
#         prefix=4 character prefix for the target volumes, mappings and consistency group e.g. TEST
#     --ask-vault-pass - The password for the vault/main.yml file where the FlashSystem/Storwize/SVC user name and password are stored
#
# Example execution:
#   ansible-playbook p_sv_create_flashcopy.yml --extra-vars '{"host": "SGC_TEST", "clustername": "jedc2-gts-fs7200-mgt1","prefix": "TEST", "fc_type": "clone"}' --ask-vault-pass
#
- name: Create a flashcopy consistency group and mappings for all volumes mapped to a host
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  vars_files:
    - vault/main.yml
  vars:
    - username: "{{ vault_spectrum_virt_user }}"
    - password: "{{ vault_spectrum_virt_password }}"

  roles:
    - ibm_sv_failures
    - ibm_sv_fc_create
    
